# Generated by Django 4.2.11 on 2024-05-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created',
        ),
    ]
